language: cpp

os: linux
dist: trusty

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
      - xorg-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev

script:
- cd src
- cd ..
- cmake .
- make -j4

before_deploy:
- GITDATE="`git show -s --date=short --format='%ad' | sed 's/-//g'`"
- GITREV="`git show -s --format='%h'`"
- BUILD_NAME="HymnToBeauty-Linux-${GITDATE}-${GITREV}.tar.gz"
- tar -czf $BUILD_NAME ./bin/Game ./bin/Editor

deploy:
  provider: releases
  api_key:
    secure: ZdeOxt4ttf+FZtG7HeUquxW1ejV69BNOXsxdn6WTOXHuSfeJxLeU0CkAhLoZ4D6yEsLKdQHyYt8ppdtXbUdvt0ZsEL64Ao5kf395WOzRpsiKx/5wOd09wJawLgIi4RoisRKrt0DHCCOt6NnCyZZeQADxhTp5YhZXegd+n5+93WkyCfc8Bi5VLf69RIaDp3zW7OQlbvtAoxyiEJDUzdSGs0IZgEh9mR0P6EDtI5bjZ8KmkQKUWV+872ZRRDiGJxNki91EiB4lKW09qgInRg3tlj6c451OCpdGnxXHGzKyk9X4FMhcUZ2fkZ5zzX64BDgJV42at8vFUY1uKuO4zrDnLXFsHXaJdnpSDEmcxC1FaZaYwz2dWAVLn0F7qhDiPywthFzsAXEocjkJNLod57wNEZGOqFBL+ps9aaVXqEOn5AQ2UBpY943uOVADJi9neg/5eEUMao58g6ZeViwmg5AhMZqpPfCmrkj0IOxzI891FQ+aAG7dNumB6cIH399Mf8afBL2TFpXCz+s7KbvGRQt2o+tWX66wGiXvUZoZ8XUEWVBo2OO9BDN7I3+Sfv300/cFwh9UuczfbKZDLOD8F0A8gnPENh8B3aq3gOkOeP3XXd0/g1QfhkZl8NCGpHzUFgEus1j96fYNywAzOjpWY6SoUnYhl+XvHDJSKtbTHR7+Jog=
  file: $BUILD_NAME
  skip_cleanup: true
  on:
    tags: true
