language: cpp

os: linux
dist: trusty

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
      - xorg-dev

script:
- cmake .
- make -j