version: '{build}'

skip_tags: true

configuration: Release

platform: x64

branches:
  only:
  - master

install:
- cmd: git submodule update --init

before_build:
- cmd: cmake -G "Visual Studio 14 2015 Win64"

build:
  project: HymnToBeauty.sln
  parallel: true
  verbosity: minimal

after_build:
  - ps: |
        $GITDATE = $(git show -s --date=short --format='%ad') -replace "-",""
        $GITREV = $(git show -s --format='%h')
        $BUILD_NAME = "HymnToBeauty-Windows-$GITDATE-$GITREV.zip" -replace " ",""
        
        $env:BUILD_NAME = $BUILD_NAME
        
        7z a -tzip $BUILD_NAME .\bin\Release\angelscript.dll .\bin\Release\assimp-vc140-mt.dll .\bin\Release\Editor.exe .\bin\Release\Engine.dll .\bin\Release\Game.exe .\bin\Release\glew32.dll .\bin\Release\glfw3.dll .\bin\Release\jsoncpp.dll .\bin\Release\openvr_api64.dll .\bin\Release\phonon.dll .\bin\Release\portaudio_x64.dll .\bin\Release\Utility.dll .\bin\Release\Video.dll

artifacts:
  - path: $(BUILD_NAME)
    name: msvcbuild
    type: zip

deploy:
  provider: GitHub
  release: nightly-$(appveyor_build_number)
  description: |
    Nightly build of Hymn to Beauty.
  auth_token:
    secure: UPPvFLF8tuplKLs7uN2lxusHQ3kUpIal8hB25+TKa+DghkNpiIYo1hxoA3IFKSE3
  artifact: msvcbuild
  draft: false
  prerelease: false
  on:
    branch: master