#version 430 compatibility
#extension GL_ARB_compute_shader : enable
#extension GL_ARB_shader_storage_buffer_object : enable

layout( std140, binding=0 ) buffer Pos
{
	vec3 particlePositions[];
};

layout( local_size_x = 128, local_size_y = 1, local_size_z = 1 ) in;

void main(void)
{
	uint gid = gl_GlobalInvocationID.x;
	
	vec3 p = particlePositions[ gid ].xyz;
	
	vec3 pp = p + vec3(1,1,2);
	
	particlePositions[ gid ].xyz = pp;
}
